apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: { app: kukuk, tier: backend }
spec:
  replicas: 1
  selector:
    matchLabels: { app: kukuk, tier: backend }
  template:
    metadata:
      labels: { app: kukuk, tier: backend }
    spec:
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: "/actuator/health", port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/actuator/health", port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
