apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels: { app: kukuk, tier: frontend }
spec:
  selector: { app: kukuk, tier: frontend }
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
